baseURL = "https://siemmt.com/"
languageCode = "fr-fr"
title = "Siem MHRETEAB"
theme = "careercanvas"

[build]
  writeStats = true

[params]
name = "Siem MHRETEAB"
tagline = "Étudiant en génie mécanique"
location = "Le Mans, France"
email = "siem21@outlook.fr"
profile_image = "/images/siem-profile.jpeg"
description = "En tant qu'étudiant en génie mécanique et productique, j'utilise les outils et techniques qui façonnent l'industrie d'aujourd'hui et de demain."
author = "Siem Mhreteab"

og_image = "images/siem-og-image.png"

hero_description = "Je prépare un Bachelor universitaire de Technologie en Génie mécanique et productique (BUT GMP) à l'IUT du Mans. Ce programme de trois ans, axé sur la pratique, met l'accent sur la conception, la fabrication et la production industrielle."
hero_location = "Le Mans, France"

linkedin_url = "https://www.linkedin.com/in/siem-mhreteab-43b622266/"
linkedin_text = "linkedin.com/in/siem-mhreteab/"

copyright = '© 2025 | Fait avec ❤️ par Romain MELLAZA'

collab_tags = [
  "Conception assistée par ordinateur (CAO)",
  "Usinage",
  "Métrologie",
  "Gestion de la production",
  "Visual Basic for Applications (VBA)"
]

resume_url_en = "/files/CV_Siem_Mhreteab_EN.pdf"
resume_url_fr = "/files/CV_Siem_Mhreteab_FR.pdf"
resume_label = "Voir le CV"

formspree_endpoint = "https://formspree.io/f/xvgbgprq" # Change to your Formspree endpoint

# Technical skills configuration
[params.technical_skills]
# FontAwesome brand icons (for special icons like Python, JS, etc.)
brand_icons = ["python", "js", "html5", "css3-alt", "linux", "docker", "github", "gitlab"]

[[params.social]]
icon = "linkedin-in"
url = "https://www.linkedin.com/in/siem-mhreteab-43b622266/"


sectionPagesMenu = 'main'

[[menu.main]]
  name = "À propos"
  url = "/#about"
  weight = 2

[[menu.main]]
  name = "Compétences"
  url = "/#skills"
  weight = 3

[[menu.main]]
  name = "Expérience"
  url = "/#experience"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 5

[[menu.main]]
  name = "Compétences techniques"
  url = "/#technical"
  weight = 4.5

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"

[server]
  [[server.headers]]
    for = "/**/*.css"
    [server.headers.values]
      Content-Type = "text/css"
